#!/bin/bash
set -e

echo -e "\nStarting container...\n======================================================="

cp /config/.kodi/userdata/advancedsettings.xml.default /config/.kodi/userdata/advancedsettings.xml
chown kodi. /config/.kodi/userdata/advancedsettings.xml
mkdir /var/cache/samba 2> /dev/null

if [ ! -z $KODI_DBHOST ] && [ ! -z $KODI_DBUSER ] && [ ! -z $KODI_DBPASS ]; then
  echo "Shared MySQL database: YES"
  sed -i -e "s/\(<host>\)\([^<]*\)\(<[^>]*\)/\1$KODI_DBHOST\3/g" /config/.kodi/userdata/advancedsettings.xml
  sed -i -e "s/\(<user>\)\([^<]*\)\(<[^>]*\)/\1$KODI_DBUSER\3/g" /config/.kodi/userdata/advancedsettings.xml
  sed -i -e "s/\(<pass>\)\([^<]*\)\(<[^>]*\)/\1$KODI_DBPASS\3/g" /config/.kodi/userdata/advancedsettings.xml
  sed -i -e "s/\(<type>\)\([^<]*\)\(<[^>]*\)/\1mysql\3/g" /config/.kodi/userdata/advancedsettings.xml
  sed -i -e "s/\(<port>\)\([^<]*\)\(<[^>]*\)/\13306\3/g" /config/.kodi/userdata/advancedsettings.xml
else
  echo "Shared MySQL database: NO"
fi

if [ -z $KODI_UPDATE_INTERVAL ]; then
  KODI_UPDATE_INTERVAL="300"
fi
if [ -z $KODI_CLEAN_INTERVAL ]; then
  KODI_CLEAN_INTERVAL="86400"
fi

function update_library_job {
  while true; do
    sleep $KODI_UPDATE_INTERVAL
    su kodi -c "kodi-send --action='UpdateLibrary(video)'" > /dev/null
    su kodi -c "kodi-send --action='UpdateLibrary(music)'" > /dev/null
  done
}

function clean_library_job {
  while true; do
    sleep $KODI_CLEAN_INTERVAL
    su kodi -c "kodi-send --action='CleanLibrary(video)'" > /dev/null
    su kodi -c "kodi-send --action='CleanLibrary(music)'" > /dev/null
  done
}

update_library_job &
echo "Automatic library update: YES (${KODI_UPDATE_INTERVAL}s)"

if [[ $KODI_CLEAN == "yes" ]] || [[ $KODI_CLEAN == "true" ]]; then
  if [ -e /config/.kodi/userdata/sources.xml ]; then
    echo "Automatic library cleaning: YES (${KODI_CLEAN_INTERVAL}s)"
    clean_library_job &
  else
    echo "Automatic library cleaning: NO (/config/.kodi/userdata/sources.xml not found)"
  fi
else
  echo "Automatic library cleaning: NO"
fi

echo "======================================================="

tail -F -q /config/.kodi/temp/kodi.log 2> /dev/null &
su kodi -c "kodi --headless"
